version: '3.1'
 
services: 

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306 
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

      # MYSQL_ROOT_PASSWORD: ""
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_ONETIME_PASSWORD: ""
      # MYSQL_INITDB_SKAIP_TZINFO: ""
      
    volumes:
      - ./data:/var/lib/mysql

volumes: 
  data: